[package]
authors = [
	"Limero",
]
edition = "2021"
readme = "README.md"
name = "tiva-rs"
version = "0.1.0"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
cortex-m-semihosting = "0.5"
panic-halt = "0.2.0"
tm4c123x-hal = { git="https://github.com/rust-embedded-community/tm4c-hal.git"  }
serde-json-core = { git = "https://github.com/japaric/serde-json-core" }
heapless = "0.7.16"
serde_derive = {version="1.0", default_features = false}
serde = {version="1.0", default_features = false}
[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3