[package]
authors = [
	"Limero",
]
edition = "2021"
readme = "README.md"
name = "tiva-rs"
version = "0.1.0"

[dependencies]
cortex-m = { version = "0.7.6", features = ["critical-section-single-core"]}
cortex-m-rt = "0.7"
cortex-m-semihosting = "0.5"
panic-halt = "0.2.0"
tm4c123x-hal = "0.10.3"
tm4c-hal="0.4.2"
# critical-section="1.0"
embedded-alloc="*"
serde-json-core = "0.5.1"
heapless = "0.7.16"
serde_derive = {version="1.0", default_features = false}
# serde = {version="1.0", default_features = false, features = ["derive","alloc"]}
serde = { version = "1.0", default-features = false }
# serde_cbor = { version = "0.11.2"}

[dependencies.linked_list_allocator]
default-features = false
version = "0.10.5"
features = ["const_mut_refs"]



[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3