[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F
runner = "qemu-system-arm -cpu cortex-m4 -machine lm3s6965evb -nographic -semihosting-config enable=on,target=native -kernel"


[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = ["-C", "link-arg=-Tlink.x","-Z","emit-stack-sizes",]